version: 0.2.0
name: example
width: 512
height: 512
palette: dell
order: random
patterns:
  - name: background
    color: black

  - name: grid
    count: 2

  - name: circle
    count: 5
    radius: 32
    
  - name: triangle
    count: 5
    edge: 3
    