name: wallpaper
width: 1920
height: 1080
palettes:
  - linkedine
  - dell
  - docker
  - google
  - gravit
  - ikea
  - microsoft
  - polaroid
  - youtube
order: random
patterns:
  - name: background
    color: white

  - name: circle
    count: 16
    radius: 64
    fill: white

  - name: circle
    count: 32
    radius: 32
    fill: white

  - name: circle
    count: 64
    radius: 16
    fill: white
