name: wallpaper
width: 1920
height: 1080
palettes:
  - blue
  - violet
  - red
  - orange
  - cyan
  - yellow
  - pink
  - green
  - gray
order: forward
patterns:
  - name: background

  - name: circle
    count: 16
    radius: 64

  - name: circle
    count: 32
    radius: 32

  - name: circle
    count: 64
    radius: 16
    fill: white
