name: logo
width: 1920
height: 1080
palettes:
  - linkedine
order: random
patterns:
  - name: background
    fill: "#421983"

  - name: file
    count: 4

  - name: file
    count: 4

  - name: file
    count: 8