name: wallpaper
width: 1920
height: 1080
palette: green
order: forward
patterns:
  - name: background
    color: white

  - name: triangle
    type: equilateral
    count: 16
    radius: 64

  - name: triangle
    type: equilateral
    count: 32
    radius: 32

  - name: triangle
    type: equilateral
    count: 64
    radius: 16
    fill: white
