name: circles
width: 1920
height: 1080
palettes:
  - blue
  - violet
  - red
  - orange
  - cyan
  - yellow
  - pink
  - green
  - gray
order: forward
patterns:
  - name: background

  - name: circle
    count: 1
    radius: 256

  - name: circle
    count: 2
    radius: 128

  - name: circle
    count: 4
    radius: 64

  - name: circle
    count: 8
    radius: 32
    fill: white
