name: example
width: 1024
height: 1024
palettes:
  - linkedine
order: forward
patterns:
  - name: background
    color: white

  - name: grid
    count: 1

  - name: circle
    count: 1
    radius: 32

  - name: triangle
    type: random
    count: 1

  - name: triangle
    type: equilateral
    count: 1
