name: linkedin
width: 1584
height: 396
palette: violet
order: straight
patterns:
  - name: background
    color: white

  - name: circle
    count: 16
    radius: 64

  - name: circle
    count: 32
    radius: 32

  - name: circle
    count: 64
    radius: 16
