name: Coverage

on:
  push:
    branches:
      - "master"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.9"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9

      - name: Install Requirements
        run: |
          pip3 install -r requirements/dev.txt
          pip3 install -r requirements/tests.txt

      - name: Generate Report
        run: coverage run -m unittest

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
